@ProductApi_HostAddress = http://localhost:5106
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlN2ExNDdmYy1hMTJiLTQ2YWUtOTZjYi1kMjA0NjhhNGU0YjMiLCJlbWFpbCI6InRlc3RlQGVtYWlsLmNvbSIsImV4cCI6MTc0MDc4MzU4OCwiaXNzIjoiYXV0aHNlcnZlciIsImF1ZCI6IlByb2R1Y3RBcGksIFBheW1lbnRBcGkifQ.ngdvGpE74pt5_S6wBo2ZWP__M7KM8Tz3TQ2duu_yLbU

GET {{ProductApi_HostAddress}}/api/products/
Accept: application/json
Authorization: {{token}}
###
